### ISSUE TITLE
多查询几条之后sqlite token失效

### ISSUE THREAD

**Issue by AugusLcz** [Rehcramon/MasterDuelCardTranslator#4]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tkinter\__init__.py", line 749, in callit
  File "MasterDuelCardTranslator.py", line 59, in update_card_detail
sqlite3.OperationalError: unrecognized token: """

**Comment by Rehcramon** [comment]
这个还希望能提供一下更详细的信息，例如当时在识别哪张卡。

目前我已知的可能出现该情况的时候是对卡名进行处理的时候，如果要删去引号则应该删2个引号，当前的版本只删除了1个。这个会在之后的版本修复。

感谢反馈。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/d25771b9e6fa063569eaf5747b63452c14446841

尝试修复了。这个issue我先close了，如果还有问题麻烦再联系我一次。
